#ifndef GOSU_BUTTONSWIN_HPP
#define GOSU_BUTTONSWIN_HPP

#ifndef DIRECTINPUT_VERSION
#define DIRECTINPUT_VERSION 0x0800
#endif
#include <dinput.h>

namespace Gosu
{
	enum ButtonName
	{
        kbRangeBegin = 1,
		kbEscape = DIK_ESCAPE,
		kbF1 = DIK_F1,
		kbF2 = DIK_F2,
		kbF3 = DIK_F3,
		kbF4 = DIK_F4,
		kbF5 = DIK_F5,
		kbF6 = DIK_F6,
		kbF7 = DIK_F7,
		kbF8 = DIK_F8,
		kbF9 = DIK_F9,
		kbF10 = DIK_F10,
		kbF11 = DIK_F11,
		kbF12 = DIK_F12,
		kb0 = DIK_0,
		kb1 = DIK_1,
		kb2 = DIK_2,
		kb3 = DIK_3,
		kb4 = DIK_4,
		kb5 = DIK_5,
		kb6 = DIK_6,
		kb7 = DIK_7,
		kb8 = DIK_8,
		kb9 = DIK_9,
		kbTab = DIK_TAB,
		kbReturn = DIK_RETURN,
		kbSpace = DIK_SPACE,
		kbLeftShift = DIK_LSHIFT,
		kbRightShift = DIK_RSHIFT,
		kbLeftControl = DIK_LCONTROL,
		kbRightControl = DIK_RCONTROL,
		kbLeftAlt = DIK_LMENU,
		kbRightAlt = DIK_RMENU,
		kbLeftMeta = DIK_LWIN,
		kbRightMeta = DIK_RWIN,
		kbBackspace = DIK_BACK,
		kbLeft = DIK_LEFT,
		kbRight = DIK_RIGHT,
		kbUp = DIK_UP,
		kbDown = DIK_DOWN,
		kbHome = DIK_HOME,
		kbEnd = DIK_END,
		kbInsert = DIK_INSERT,
		kbDelete = DIK_DELETE,
		kbPageUp = DIK_PRIOR,
		kbPageDown = DIK_NEXT,
		kbEnter = DIK_NUMPADENTER,
		kbNumpad0 = DIK_NUMPAD0,
		kbNumpad1 = DIK_NUMPAD1,
		kbNumpad2 = DIK_NUMPAD2,
		kbNumpad3 = DIK_NUMPAD3,
		kbNumpad4 = DIK_NUMPAD4,
		kbNumpad5 = DIK_NUMPAD5,
		kbNumpad6 = DIK_NUMPAD6,
		kbNumpad7 = DIK_NUMPAD7,
		kbNumpad8 = DIK_NUMPAD8,
		kbNumpad9 = DIK_NUMPAD9,
		kbNumpadAdd = DIK_ADD,
		kbNumpadSubtract = DIK_SUBTRACT,
		kbNumpadMultiply = DIK_MULTIPLY,
		kbNumpadDivide = DIK_DIVIDE,
		kbRangeEnd = 0xff,

        msRangeBegin,
        msLeft = msRangeBegin,
        msRight,
        msMiddle,
        msWheelUp,
        msWheelDown,
        msRangeEnd,
        
        gpRangeBegin,
        gpLeft = gpRangeBegin,
        gpRight,
        gpUp,
        gpDown,
        gpButton0,
        gpButton1,
        gpButton2,
        gpButton3,
        gpButton4,
        gpButton5,
        gpButton6,
        gpButton7,
        gpButton8,
        gpButton9,
        gpButton10,
        gpButton11,
        gpButton12,
        gpButton13,
        gpButton14,
        gpButton15,
        gpRangeEnd = gpButton15,
        
        kbNum = kbRangeEnd - kbRangeBegin + 1,
        msNum = msRangeEnd - msRangeBegin + 1,
        gpNum = gpRangeEnd - gpRangeBegin + 1,
        
        numButtons = gpRangeEnd,
		noButton = 0xffffffff
	};
}

#endif
