require 'ftools'
require 'rake/gempackagetask'

GOSU_VERSION = ENV['GOSU_RELEASE_VERSION']
throw "GOSU_RELEASE_VERSION must be set" if GOSU_VERSION.nil?

COMMON_FILES = FileList[
  'COPYING.txt',
  'README.txt',
]

COMMON_CPP_FILES = COMMON_FILES + FileList[
  'examples/*.cpp',
  'examples/media/*',
  'reference/**/*',
]

COMMON_RUBY_FILES = COMMON_FILES + FileList[
  'examples/*.rb',
  'examples/media/*',
]

SOURCE_FILES = COMMON_CPP_FILES + COMMON_RUBY_FILES + FileList[
  'Rakefile',
  'Gosu/**/*', 'GosuImpl/**/*',
  'linux/configure', 'linux/configure.ac', 'linux/Makefile.in',
  'mac/Gosu.xcodeproj/**/*', 'mac/*.a', 'mac/English.lproj/**/*',
  'mac/Gosu-Info.plist', 'mac/RubyGosu Template-Info.plist',
  'windows/**/*',
]

BASE_SPEC = Gem::Specification.new do |s|
  #### Basic information.
  s.name = 'gosu'
  s.version = GOSU_VERSION
  s.platform = 'placeholder'
  s.summary = '2D game development library.'
  s.description = <<EOS
  2D game development library.
  
  Gosu features easy to use and game-friendly interfaces to 2D graphics
  and text (accelerated by 3D hardware), sound samples and music as well as
  keyboard, mouse and gamepad/joystick input.
  
  Also includes demos for integration with RMagick, Chipmunk and Ruby-OpenGL.
EOS
  s.authors = ['Julian Raschke', 'Jan Luecker']
  s.date = Time.now.strftime '%Y-%m-%d'
  s.email = 'julian@raschke.de'
  s.files = ['placeholder']
  s.homepage = 'http://code.google.com/p/gosu/'
  s.require_paths = ['lib']
  s.required_ruby_version = Gem::Requirement.new('>= 1.8.2')
  s.summary = '2D game development library.'
end

desc "Build C++ reference with doxygen"
task :cpp_docs do
  sh "cd reference && doxygen"
end

Rake.application.in_namespace :mac do
  desc "Build Gosu.framework"
  task :cpp => :cpp_docs do
    sh "cd mac && xcodebuild -project Gosu.xcodeproj -target Gosu -configuration Release"
  end

  desc "Build lib/gosu.bundle and RubyGosu Deployment Template.app"
  task :ruby do
    sh "cd mac && xcodebuild -project Gosu.xcodeproj -target 'RubyGosu Core' -configuration Release"
    sh "cd mac && xcodebuild -project Gosu.xcodeproj -target 'RubyGosu Deployment Template' -configuration Release"
  end

  MAC_ARCHIVE_FILENAME = "public/gosu-mac-#{GOSU_VERSION}.tar.gz"

  desc "Build the archive #{MAC_ARCHIVE_FILENAME}"
  task :archive => [:cpp, :ruby] do
    files = COMMON_CPP_FILES + COMMON_RUBY_FILES + ['lib/gosu.bundle'] +
            FileList['Gosu.framework/**/*', 'RubyGosu Deployment Template.app/**/*']
    sh "tar -czf #{MAC_ARCHIVE_FILENAME} #{files.map { |filename| "'#{filename}'" }.join(' ')}"
  end

  desc "Releases the archive #{MAC_ARCHIVE_FILENAME} on GoogleCode"
  task :release => :archive do
    sh "./googlecode_upload.py --summary=\"Gosu #{GOSU_VERSION} precompiled for Mac OS X (C++ & Ruby)\"" +
       " --project=gosu --user=julianraschke --labels=\"Featured,Type-Archive,OpSys-OSX\" #{MAC_ARCHIVE_FILENAME}"
  end

  task :gem => :ruby

  MAC_SPEC = BASE_SPEC.dup
  MAC_SPEC.platform = 'universal-darwin'
  MAC_SPEC.files = COMMON_RUBY_FILES + ['lib/gosu.bundle']
  Rake::GemPackageTask.new(MAC_SPEC) { |t| t.package_dir = 'public/mac_gem' }
end

# TODO: Windows tasks

Rake.application.in_namespace :win do
  WINDOWS_CPP_ARCHIVE_FILENAME = "public/gosu-windows-cpp-#{GOSU_VERSION}.zip"
  
  desc "Build the archive #{MAC_ARCHIVE_FILENAME}"
  task :archive do #=> [:cpp, :ruby] do
    files = COMMON_CPP_FILES + ['lib/Gosu.lib', 'lib/GosuDebug.lib']
    sh "zip #{WINDOWS_CPP_ARCHIVE_FILENAME} #{files.map { |filename| "'#{filename}'" }.join(' ')}"
  end

  WINDOWS_RUBY_ARCHIVE_FILENAME = "public/gosu-windows-ruby-#{GOSU_VERSION}.zip"

end

Rake.application.in_namespace :linux do
  LINUX_ARCHIVE_FILENAME = "public/gosu-source-#{GOSU_VERSION}.tar.gz"

  desc "Build the archive #{LINUX_ARCHIVE_FILENAME}"
  task :archive => [:build, :cpp_reference] do
    files = COMMON_CPP_FILES + COMMON_RUBY_FILES
    sh "tar -czf #{LINUX_ARCHIVE_FILENAME} #{files.map { |filename| "'#{filename}'" }.join(' ')}"
  end

  desc "Releases the archive #{LINUX_ARCHIVE_FILENAME} on GoogleCode"
  task :release => :archive do
    #TODO
    #sh "./googlecode_upload.py --summary=\"Gosu #{GOSU_VERSION} precompiled for Mac OS X (C++ & Ruby)\"" +
    #   " --project=gosu --user=julianraschke --labels=\"Featured,Type-Archive,OpSys-OSX\" #{MAC_ARCHIVE_FILENAME}"
  end

  LINUX_SPEC = BASE_SPEC.dup
  LINUX_SPEC.platform = 'ruby'
  LINUX_SPEC.files = COMMON_RUBY_FILES + ['linux/configure.ac', 'linux/Makefile.in', 'linux/extconf.rb', "Ruby Source TODO"]
  LINUX_SPEC.extensions = [ 'linux/extconf.rb' ]
  LINUX_SPEC.require_path = 'lib'
  LINUX_SPEC.requirements = ['g++',
                             'pkg-config',
                             'libgl',
                             'X11 includes and libraries',
                             'pangoft2',
                             'fmod or SDL_mixer',

                             "(Packages for Debian/Ubuntu:\n" +
                             ' g++ pkg-config ruby-dev xorg-dev' +
                             ' libsdl-mixer1.2-dev libgl1-mesa-dev libglu1-mesa-dev' +
                             ' libpango1.0-dev' +
                             "\n)"]
  
  Rake::GemPackageTask.new(LINUX_SPEC) { |t| t.package_dir = 'public/linux_gem' }
end

# TODO? Gem upload to RubyForge: http://nubyonrails.com/articles/tutorial-publishing-rubygems-with-hoe

