/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.28.3-0-g8a5ba43d0 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.28.3-0-g8a5ba43d0"
#endif
#define SDL_REVISION_NUMBER 0
