/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.26.5-0-gac13ca9ab (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.26.5-0-gac13ca9ab"
#endif
#define SDL_REVISION_NUMBER 0
