platform :osx, "10.7"

target "Tutorial" do
  pod "Gosu", path: "../.."
  
  # In a real project, you would use this instead of a relative path:
  # pod "Gosu", git: "https://github.com/gosu/gosu.git"
end
